### ISSUE TITLE
Merging maps within structs

### ISSUE THREAD

**Issue by Jmeyering** [imdario/mergo#11]
Considering this example

```go
type Test struct {
      A map[string]string
      B string
      C string
      
}

func test() {
      foo := new(Test)
      foo.B = "one"

      bar := new(Test)
      bar.A = map[string]string{"biz": "baz"}
      bar.B = "two"
      bar.C = "three"

      mergo.Merge(foo, bar)
}
```

What am I doing wrong to be getting this error?

Adding This line solves the problem and merges happen as expected. But its not ideal.

`Foo.A = map[string]string{}`

```
panic: assignment to entry in nil map

goroutine 1 [running]:
reflect.Value.SetMapIndex(0x8123380, 0x184382a8, 0xd5, 0x8122d80, 0x1840a178, 0x58, 0x8122d80, 0x1840a180, 0x58)
        /usr/local/go/src/reflect/value.go:1440 +0x21a
github.com/imdario/mergo.deepMerge(0x8123380, 0x184382a8, 0xd5, 0x8123380, 0x184382b8, 0xd5, 0x18436480, 0x1, 0x0, 0x0)
        /home/vagrant/go/src/github.com/imdario/mergo/merge.go:56 +0x7b3
github.com/imdario/mergo.deepMerge(0x813e540, 0x184382a0, 0xd9, 0x813e540, 0x184382b0, 0xd9, 0x18436480, 0x0, 0x0, 0x0)
        /home/vagrant/go/src/github.com/imdario/mergo/merge.go:36 +0x9a5
github.com/imdario/mergo.Merge(0x811b080, 0x184382a0, 0x811b080, 0x184382b0, 0x0, 0x0)
        /home/vagrant/go/src/github.com/imdario/mergo/merge.go:96 +0x1bb
main.test()
        /home/vagrant/go/src/github.com/Jmeyering/zealot/main.go:38 +0x12e
main.main()
        /home/vagrant/go/src/github.com/Jmeyering/zealot/main.go:41 +0x28

goroutine 2 [runnable]:
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:90
runtime.goexit()
        /usr/local/go/src/runtime/asm_386.s:2287 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
        /usr/local/go/src/runtime/mgc0.go:82
runtime.goexit()
        /usr/local/go/src/runtime/asm_386.s:2287 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
        /usr/local/go/src/runtime/malloc.go:712
runtime.goexit()
        /usr/local/go/src/runtime/asm_386.s:2287 +0x1
exit status 2
```

**Comment by imdario** [comment]
Sorry, I didn't see your issue. Probably I could check it in the next weeks to improve the way Mergo works in this case.

**Comment by Jmeyering** [comment]
I closed because my example had a problem that ended up being a case of me not RTFM.

However I did have a question regarding deep merging slices.

Example would be having two structs with a field of `[]string` and instead of completely overwriting, appending values on to do a true deep merge.

Thoughts on this?

**Comment by imdario** [comment]
That's a nice idea but it would be confusing due the way of work of Mergo. It works on zero values so appending values isn't exactly the same.

I don't know right now how to handle this good idea in a proper and non-confusing way.
