### ISSUE TITLE
Can't pass yaml Unmarshalled map[string]interface as src to Merge()

### ISSUE THREAD

**Issue by tn185075** [imdario/mergo#164]
I have tried to pass 
*  json unmarshalled map[string]interface{} as dst,
*  yaml unmarshalled map[string]interface{} as src,

then this error comes up,
> PANIC: reflect.Value.MapIndex: value of type interface {} is not assignable to type string
goroutine 36 [running]:
github.com/codegangsta/negroni.(*Recovery).ServeHTTP.func1(0x11080d0, 0xc000090298, 0xc0000c8280, 0xc000098300)
        C:/Users/TN185075/go/pkg/mod/github.com/codegangsta/negroni@v1.0.0/recovery.go:159 +0xd2
panic(0x8d7020, 0xc000057df0)
        c:/go/src/runtime/panic.go:969 +0x174
reflect.Value.assignTo(0x8f3680, 0xc000057d50, 0x94, 0x9a11c5, 0x16, 0x8d7020, 0x0, 0x8f3680, 0xc000057d50, 0x94)
        c:/go/src/reflect/value.go:2411 +0x42d
reflect.Value.MapIndex(0x9000e0, 0xc00007d920, 0x15, 0x8f3680, 0xc000057d50, 0x94, 0x8f3680, 0xc000057de0, 0x94)
        c:/go/src/reflect/value.go:1165 +0xf1
github.com/imdario/mergo.deepMerge(0x9000e0, 0xc00007d920, 0x15, 0x8feb20, 0xc00007dc80, 0x15, 0xc0001ab1a0, 0x2, 0xc000004cc0, 0x0, ...)
        C:/Users/TN185075/go/pkg/mod/github.com/imdario/mergo@v0.3.11/merge.go:119 +0x4a9
github.com/imdario/mergo.deepMerge(0x9000e0, 0xc000056ef8, 0x195, 0x9000e0, 0xc000057ca8, 0x95, 0xc0001ab1a0, 0x1, 0xc000004cc0, 0x0, ...)
        C:/Users/TN185075/go/pkg/mod/github.com/imdario/mergo@v0.3.11/merge.go:147 +0xa6e
github.com/imdario/mergo.deepMerge(0x926ea0, 0xc000056ef0, 0x199, 0x926ea0, 0xc000057ca0, 0x99, 0xc0001ab1a0, 0x0, 0xc000004cc0, 0x99, ...)
        C:/Users/TN185075/go/pkg/mod/github.com/imdario/mergo@v0.3.11/merge.go:93 +0x2f89
github.com/imdario/mergo.merge(0x8c1e00, 0xc000056ef0, 0x926ea0, 0xc000057ca0, 0xc0001ab300, 0x1, 0x1, 0x0, 0x5)
        C:/Users/TN185075/go/pkg/mod/github.com/imdario/mergo@v0.3.11/merge.go:361 +0x331
github.com/imdario/mergo.Merge(...)
        C:/Users/TN185075/go/pkg/mod/github.com/imdario/mergo@v0.3.11/merge.go:291

but the reverse still works.

I rectified this by marshalling yaml content to json, and unmarshal again from json and pass it to src, then it worked like magic.😂

**Comment by tn185075** [comment]
I got this resolved by using latest yaml release for Go. Thanks for making my work easy mergo 🙌
