### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [recovered]

### ISSUE THREAD

**Issue by aanm** [imdario/mergo#17]
I'm getting an error
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xa0 pc=0x535086]

goroutine 24 [running]:
testing.tRunner.func1(0xc82012e510)
        /usr/local/go/src/testing/testing.go:450 +0x171
github.com/imdario/mergo.deepMerge(0x8057e0, 0xc82014f5c0, 0x15, 0x8057e0, 0xc82014f050, 0x15, 0xc820051b28, 0x2, 0x1, 0x0, ...)
        github.com/imdario/mergo/merge.go:49 +0x836
github.com/imdario/mergo.deepMerge(0x802ea0, 0xc820168e10, 0x54, 0x802ea0, 0xc820168e00, 0x54, 0xc8200b3b18, 0x1, 0x1, 0x0, ...)
        github.com/imdario/mergo/merge.go:73 +0x556
github.com/imdario/mergo.deepMerge(0x8057e0, 0xc8200e93f0, 0xd5, 0x8057e0, 0xc82014f170, 0x15, 0xc8200b3b18, 0x0, 0xc82014f101, 0x0, ...)
        github.com/imdario/mergo/merge.go:53 +0x8c9
github.com/imdario/mergo.merge(0x7e6040, 0xc8200e93f0, 0x8057e0, 0xc82014f170, 0xc820134d01, 0x0, 0x0)
        github.com/imdario/mergo/merge.go:109 +0x2cd
github.com/imdario/mergo.MergeWithOverwrite(0x7e6040, 0xc8200e93f0, 0x8057e0, 0xc82014f170, 0x0, 0x0)
        github.com/imdario/mergo/merge.go:95 +0x50
```

**Comment by imdario** [comment]
Please, can you provide an example showing how are you calling MergeWithOverwrite and what kind of parameters?

**Comment by aanm** [comment]
@imdario Sorry for the delay, my example was more complex so I had to create a simple one.
I also tried with `MapWithOverwrite` and got the same output, what is the difference between `MapWithOverwrite` and `MergeWithOverwrite`?

```go
package test

import (
	"encoding/json"
	"testing"

	"github.com/imdario/mergo"
)

var (
	request    = `{"timestamp":null, "name": "foo"}`
	maprequest = map[string]interface{}{
		"timestamp": nil,
		"name":      "foo",
		"newStuff":  "foo",
	}
)

func TestMergeWithOverwrite(t *testing.T) {
	var something map[string]interface{}
	if err := json.Unmarshal([]byte(request), &something); err != nil {
		t.Errorf("Error while Unmarshalling maprequest %s", err)
	}
	if err := mergo.MergeWithOverwrite(&something, maprequest); err != nil {
		t.Errorf("Error while merging %s", err)
	}
}
```

**Comment by imdario** [comment]
Ok, working on it. I add it as an unit test and I'm checking it.

**Comment by imdario** [comment]
Done. There was missing an "if" to check if the value from src was nil. I should check if there is another corner case like this in other points of the code.
